"use client";
import { useState } from "react";
import { Card, CardBody, CardHeader } from "@/components/ui/Card";
import { FieldGroup, Input, Row, Select, Textarea, NumberInput } from "@/components/ui/Field";
import { CodeBlock } from "@/components/shell/TextOutput";
import { useBusiness } from "../shared/Business";

type Kind = "LocalBusiness" | "Product" | "Article" | "Organization" | "HowTo" | "Event";
const BIZ_TYPES = ["LocalBusiness", "Store", "Restaurant", "CafeOrCoffeeShop", "GroceryStore", "ClothingStore", "ElectronicsStore", "JewelryStore", "MedicalClinic", "Dentist", "BeautySalon", "HealthClub", "AutoRepair", "RealEstateAgent", "ProfessionalService", "Hotel", "TravelAgency", "EducationalOrganization"];

export default function SchemaMarkup() {
  const { business } = useBusiness();
  const [kind, setKind] = useState<Kind>("LocalBusiness");
  const [b, setB] = useState({ type: "Store", name: business.name, url: "https://www.example.in", phone: business.phone, street: business.address, city: "New Delhi", state: "Delhi", pin: "110001", hours: "Mo-Sa 10:00-20:00", price: "₹₹", lat: "", lng: "", image: "", rating: 4.6, reviews: 120 });
  const [p, setP] = useState({ name: "Basmati Rice 5 kg", brand: business.name, sku: "RICE-5KG", price: 499, currency: "INR", availability: "InStock", desc: "Premium aged basmati.", image: "", rating: 4.5, reviews: 32, url: "" });
  const [a, setA] = useState({ headline: "How to file GSTR-3B in 10 minutes", author: "Priya Verma", published: new Date().toISOString().slice(0, 10), modified: "", image: "", desc: "", url: "" });
  const [h, setH] = useState({ name: "How to set up a UPI QR standee", total: "PT10M", steps: "Enter your UPI ID\nPick a colour theme\nDownload the PDF and print" });
  const [e, setE] = useState({ name: "Diwali Mela 2026", start: "2026-11-06T17:00", end: "2026-11-08T22:00", venue: "Community Ground", city: "Jaipur", price: 0, url: "" });

  const site = { "@type": "Organization", name: business.name, url: b.url, telephone: b.phone, email: business.email || undefined };
  let obj: Record<string, unknown> = {};
  if (kind === "LocalBusiness") obj = { "@context": "https://schema.org", "@type": b.type, name: b.name, url: b.url, telephone: b.phone, image: b.image || undefined, priceRange: b.price, address: { "@type": "PostalAddress", streetAddress: b.street.replace(/\n/g, ", "), addressLocality: b.city, addressRegion: b.state, postalCode: b.pin, addressCountry: "IN" }, geo: b.lat && b.lng ? { "@type": "GeoCoordinates", latitude: parseFloat(b.lat), longitude: parseFloat(b.lng) } : undefined, openingHours: b.hours, aggregateRating: b.reviews ? { "@type": "AggregateRating", ratingValue: b.rating, reviewCount: b.reviews } : undefined };
  if (kind === "Organization") obj = { "@context": "https://schema.org", ...site, logo: b.image || undefined, address: { "@type": "PostalAddress", streetAddress: b.street.replace(/\n/g, ", "), addressLocality: b.city, addressRegion: b.state, postalCode: b.pin, addressCountry: "IN" } };
  if (kind === "Product") obj = { "@context": "https://schema.org", "@type": "Product", name: p.name, image: p.image || undefined, description: p.desc, sku: p.sku, brand: { "@type": "Brand", name: p.brand }, offers: { "@type": "Offer", url: p.url || undefined, priceCurrency: p.currency, price: p.price, availability: `https://schema.org/${p.availability}`, itemCondition: "https://schema.org/NewCondition", seller: { "@type": "Organization", name: business.name } }, aggregateRating: p.reviews ? { "@type": "AggregateRating", ratingValue: p.rating, reviewCount: p.reviews } : undefined };
  if (kind === "Article") obj = { "@context": "https://schema.org", "@type": "Article", headline: a.headline, description: a.desc || undefined, image: a.image || undefined, author: { "@type": "Person", name: a.author }, publisher: { "@type": "Organization", name: business.name, logo: b.image ? { "@type": "ImageObject", url: b.image } : undefined }, datePublished: a.published, dateModified: a.modified || a.published, mainEntityOfPage: a.url || undefined };
  if (kind === "HowTo") obj = { "@context": "https://schema.org", "@type": "HowTo", name: h.name, totalTime: h.total, step: h.steps.split("\n").filter(Boolean).map((s, i) => ({ "@type": "HowToStep", position: i + 1, name: s.trim(), text: s.trim() })) };
  if (kind === "Event") obj = { "@context": "https://schema.org", "@type": "Event", name: e.name, startDate: e.start, endDate: e.end, eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode", eventStatus: "https://schema.org/EventScheduled", location: { "@type": "Place", name: e.venue, address: { "@type": "PostalAddress", addressLocality: e.city, addressCountry: "IN" } }, organizer: { "@type": "Organization", name: business.name }, offers: { "@type": "Offer", price: e.price, priceCurrency: "INR", availability: "https://schema.org/InStock", url: e.url || undefined } };
  const clean = JSON.parse(JSON.stringify(obj));
  const code = `<script type="application/ld+json">\n${JSON.stringify(clean, null, 2)}\n</script>`;

  return (
    <div className="grid gap-5 lg:grid-cols-12 items-start">
      <Card className="lg:col-span-6 min-w-0">
        <CardHeader title="Schema details" />
        <CardBody className="grid gap-6">
          <Select label="Schema type" value={kind} onChange={(x) => setKind(x.target.value as Kind)} options={[{ value: "LocalBusiness", label: "Local business (shop, clinic, restaurant)" }, { value: "Organization", label: "Organization / brand" }, { value: "Product", label: "Product" }, { value: "Article", label: "Article / blog post" }, { value: "HowTo", label: "How-to" }, { value: "Event", label: "Event" }]} />
          {kind === "LocalBusiness" || kind === "Organization" ? (
            <FieldGroup title="Business">
              {kind === "LocalBusiness" ? <Select label="Business type" value={b.type} onChange={(x) => setB({ ...b, type: x.target.value })} options={BIZ_TYPES} /> : null}
              <Row><Input label="Name" value={b.name} onChange={(x) => setB({ ...b, name: x.target.value })} /><Input label="Website" value={b.url} onChange={(x) => setB({ ...b, url: x.target.value })} /><Input label="Phone" value={b.phone} onChange={(x) => setB({ ...b, phone: x.target.value })} /><Input label="Logo / image URL" value={b.image} onChange={(x) => setB({ ...b, image: x.target.value })} /></Row>
              <Textarea label="Street address" rows={2} value={b.street} onChange={(x) => setB({ ...b, street: x.target.value })} />
              <Row cols={3}><Input label="City" value={b.city} onChange={(x) => setB({ ...b, city: x.target.value })} /><Input label="State" value={b.state} onChange={(x) => setB({ ...b, state: x.target.value })} /><Input label="PIN" value={b.pin} onChange={(x) => setB({ ...b, pin: x.target.value })} /></Row>
              {kind === "LocalBusiness" ? <><Row><Input label="Opening hours" value={b.hours} onChange={(x) => setB({ ...b, hours: x.target.value })} help="e.g. Mo-Sa 10:00-20:00" /><Select label="Price range" value={b.price} onChange={(x) => setB({ ...b, price: x.target.value })} options={["₹", "₹₹", "₹₹₹", "₹₹₹₹"]} /><Input label="Latitude" value={b.lat} onChange={(x) => setB({ ...b, lat: x.target.value })} /><Input label="Longitude" value={b.lng} onChange={(x) => setB({ ...b, lng: x.target.value })} /><NumberInput label="Rating" value={b.rating} onChange={(v) => setB({ ...b, rating: v })} step={0.1} max={5} /><NumberInput label="Review count" value={b.reviews} onChange={(v) => setB({ ...b, reviews: v })} /></Row></> : null}
            </FieldGroup>
          ) : null}
          {kind === "Product" ? <FieldGroup title="Product"><Row><Input label="Name" value={p.name} onChange={(x) => setP({ ...p, name: x.target.value })} /><Input label="Brand" value={p.brand} onChange={(x) => setP({ ...p, brand: x.target.value })} /><Input label="SKU" value={p.sku} onChange={(x) => setP({ ...p, sku: x.target.value })} /><NumberInput label="Price" prefix="₹" value={p.price} onChange={(v) => setP({ ...p, price: v })} /><Select label="Availability" value={p.availability} onChange={(x) => setP({ ...p, availability: x.target.value })} options={["InStock", "OutOfStock", "PreOrder", "LimitedAvailability"]} /><Input label="Product URL" value={p.url} onChange={(x) => setP({ ...p, url: x.target.value })} /><Input label="Image URL" value={p.image} onChange={(x) => setP({ ...p, image: x.target.value })} wrapClassName="sm:col-span-2" /><NumberInput label="Rating" value={p.rating} onChange={(v) => setP({ ...p, rating: v })} step={0.1} max={5} /><NumberInput label="Review count" value={p.reviews} onChange={(v) => setP({ ...p, reviews: v })} /></Row><Textarea label="Description" rows={2} value={p.desc} onChange={(x) => setP({ ...p, desc: x.target.value })} /></FieldGroup> : null}
          {kind === "Article" ? <FieldGroup title="Article"><Input label="Headline" value={a.headline} onChange={(x) => setA({ ...a, headline: x.target.value })} /><Row><Input label="Author" value={a.author} onChange={(x) => setA({ ...a, author: x.target.value })} /><Input label="Article URL" value={a.url} onChange={(x) => setA({ ...a, url: x.target.value })} /><Input label="Published" type="date" value={a.published} onChange={(x) => setA({ ...a, published: x.target.value })} /><Input label="Modified" type="date" value={a.modified} onChange={(x) => setA({ ...a, modified: x.target.value })} /><Input label="Image URL" value={a.image} onChange={(x) => setA({ ...a, image: x.target.value })} wrapClassName="sm:col-span-2" /></Row><Textarea label="Description" rows={2} value={a.desc} onChange={(x) => setA({ ...a, desc: x.target.value })} /></FieldGroup> : null}
          {kind === "HowTo" ? <FieldGroup title="How-to"><Input label="Title" value={h.name} onChange={(x) => setH({ ...h, name: x.target.value })} /><Input label="Total time (ISO 8601)" value={h.total} onChange={(x) => setH({ ...h, total: x.target.value })} help="PT10M = 10 minutes, PT2H = 2 hours" /><Textarea label="Steps (one per line)" rows={5} value={h.steps} onChange={(x) => setH({ ...h, steps: x.target.value })} /></FieldGroup> : null}
          {kind === "Event" ? <FieldGroup title="Event"><Input label="Event name" value={e.name} onChange={(x) => setE({ ...e, name: x.target.value })} /><Row><Input label="Starts" type="datetime-local" value={e.start} onChange={(x) => setE({ ...e, start: x.target.value })} /><Input label="Ends" type="datetime-local" value={e.end} onChange={(x) => setE({ ...e, end: x.target.value })} /><Input label="Venue" value={e.venue} onChange={(x) => setE({ ...e, venue: x.target.value })} /><Input label="City" value={e.city} onChange={(x) => setE({ ...e, city: x.target.value })} /><NumberInput label="Ticket price" prefix="₹" value={e.price} onChange={(v) => setE({ ...e, price: v })} /><Input label="Tickets URL" value={e.url} onChange={(x) => setE({ ...e, url: x.target.value })} /></Row></FieldGroup> : null}
        </CardBody>
      </Card>
      <div className="lg:col-span-6 min-w-0 lg:sticky lg:top-24"><CodeBlock value={code} label={`JSON-LD · ${kind}`} filename={`${kind.toLowerCase()}-schema.html`} mime="text/html" /><p className="mt-3 text-xs text-muted">Paste inside &lt;head&gt;. Test with Google’s Rich Results Test or validator.schema.org. Empty fields are omitted automatically.</p></div>
    </div>
  );
}
