"use client";
import { SimpleCalc, type CalcSpec, n, safeDiv, inr, num, pct } from "@/components/shell/SimpleCalc";
import { fmtDate, addDaysISO, todayISO } from "@/lib/format";

const days = (a: string, b: string) => Math.round((new Date(b + "T00:00:00").getTime() - new Date(a + "T00:00:00").getTime()) / 86400000);
const money = (x: number) => inr(x, { decimals: 0 });

export const specs: Record<string, CalcSpec> = {
  /* ─────────── Marketing & sales ─────────── */
  "cac-calculator": {
    inputs: [
      { key: "mkt", label: "Marketing spend", type: "currency", default: 120000, half: true, group: "Period spend" },
      { key: "sales", label: "Sales spend (salaries, tools)", type: "currency", default: 80000, half: true, group: "Period spend" },
      { key: "cust", label: "New customers won", type: "number", default: 250, half: true, group: "Results" },
      { key: "arpu", label: "Avg revenue per customer / year", type: "currency", default: 3000, half: true, group: "Results" },
      { key: "margin", label: "Gross margin", type: "percent", default: 40, half: true, group: "Results" },
      { key: "life", label: "Avg customer lifetime", type: "years", default: 2, half: true, group: "Results", step: 0.5 },
    ],
    compute: (v) => {
      const spend = n(v.mkt) + n(v.sales); const cac = safeDiv(spend, n(v.cust));
      const ltv = n(v.arpu) * (n(v.margin) / 100) * n(v.life); const ratio = safeDiv(ltv, cac);
      return { primary: { label: "Customer acquisition cost", value: inr(cac), sub: `${money(spend)} spent to win ${num(n(v.cust))} customers` }, tiles: [{ label: "LTV (gross)", value: money(ltv) }, { label: "LTV : CAC", value: `${num(ratio, 1)}×`, tone: ratio >= 3 ? "accent" : ratio >= 1 ? "warn" : "danger" }, { label: "Payback", value: `${num(safeDiv(cac, n(v.arpu) * (n(v.margin) / 100) / 12), 1)} mo` }], insight: ratio >= 3 ? "Healthy: a 3:1 or better LTV:CAC ratio means acquisition is profitable." : ratio >= 1 ? "Marginal: aim for LTV at least 3× CAC by improving retention or cutting spend." : "Unprofitable: you spend more to win a customer than they return." };
    },
    formula: "CAC = (marketing + sales spend) ÷ new customers · LTV = ARPU × margin × lifetime",
  },
  "retention-rate": {
    inputs: [
      { key: "start", label: "Customers at start of period", type: "number", default: 500, half: true },
      { key: "end", label: "Customers at end of period", type: "number", default: 540, half: true },
      { key: "acq", label: "New customers acquired during period", type: "number", default: 90 },
    ],
    compute: (v) => { const crr = safeDiv(n(v.end) - n(v.acq), n(v.start)) * 100; return { primary: { label: "Customer retention rate", value: pct(crr, 1), sub: `${num(n(v.start) - (n(v.end) - n(v.acq)))} customers lost` }, tiles: [{ label: "Churn rate", value: pct(100 - crr, 1), tone: 100 - crr > 20 ? "danger" : "default" }, { label: "Retained", value: num(n(v.end) - n(v.acq)) }] }; },
    formula: "CRR = (customers at end − new customers) ÷ customers at start × 100",
  },
  "referral-rate": {
    inputs: [{ key: "total", label: "Total new customers", type: "number", default: 300, half: true }, { key: "ref", label: "Came via referral / word of mouth", type: "number", default: 66, half: true }, { key: "spend", label: "Referral rewards paid", type: "currency", default: 0 }],
    compute: (v) => { const r = safeDiv(n(v.ref), n(v.total)) * 100; return { primary: { label: "Referral rate", value: pct(r, 1) }, tiles: [{ label: "Referred customers", value: num(n(v.ref)) }, { label: "Cost per referral", value: n(v.spend) ? inr(safeDiv(n(v.spend), n(v.ref))) : "—" }], insight: r >= 20 ? "Strong organic growth — customers actively recommend you." : "Consider a simple referral reward to lift word-of-mouth above 20%." }; },
    formula: "Referral rate = referred customers ÷ total new customers × 100",
  },
  "roas-calculator": {
    inputs: [{ key: "spend", label: "Ad spend", type: "currency", default: 50000, half: true }, { key: "rev", label: "Revenue from ads", type: "currency", default: 210000, half: true }, { key: "margin", label: "Gross margin on those sales", type: "percent", default: 35, half: true }, { key: "conv", label: "Conversions", type: "number", default: 140, half: true }],
    compute: (v) => { const roas = safeDiv(n(v.rev), n(v.spend)); const profit = n(v.rev) * (n(v.margin) / 100) - n(v.spend); const be = safeDiv(1, n(v.margin) / 100); return { primary: { label: "Return on ad spend", value: `${num(roas, 2)}×`, sub: `Every ₹1 on ads returned ₹${num(roas, 2)}` }, tiles: [{ label: "Profit after ads", value: money(profit), tone: profit >= 0 ? "accent" : "danger" }, { label: "Break-even ROAS", value: `${num(be, 2)}×` }, { label: "Cost per conversion", value: inr(safeDiv(n(v.spend), n(v.conv))) }], insight: roas >= be ? `Above break-even (${num(be, 2)}×). Campaign is profitable.` : `Below break-even (${num(be, 2)}×). Improve conversion or cut CPC.` }; },
    formula: "ROAS = ad revenue ÷ ad spend · break-even ROAS = 1 ÷ gross margin",
  },
  "lead-conversion": {
    inputs: [{ key: "leads", label: "Total leads / enquiries", type: "number", default: 420, half: true }, { key: "won", label: "Converted to customers", type: "number", default: 63, half: true }, { key: "spend", label: "Lead generation spend", type: "currency", default: 0, half: true }, { key: "aov", label: "Avg order value", type: "currency", default: 0, half: true }],
    compute: (v) => { const r = safeDiv(n(v.won), n(v.leads)) * 100; return { primary: { label: "Lead conversion rate", value: pct(r, 1), sub: `${num(n(v.won))} of ${num(n(v.leads))} leads converted` }, tiles: [{ label: "Cost per lead", value: n(v.spend) ? inr(safeDiv(n(v.spend), n(v.leads))) : "—" }, { label: "Cost per customer", value: n(v.spend) ? inr(safeDiv(n(v.spend), n(v.won))) : "—" }, { label: "Revenue generated", value: n(v.aov) ? money(n(v.aov) * n(v.won)) : "—" }] }; },
    formula: "Conversion rate = converted ÷ total leads × 100",
  },
  "win-rate": {
    inputs: [{ key: "opp", label: "Opportunities (qualified)", type: "number", default: 80, half: true }, { key: "won", label: "Deals won", type: "number", default: 22, half: true }, { key: "lost", label: "Deals lost", type: "number", default: 40, half: true }, { key: "value", label: "Avg deal value", type: "currency", default: 0, half: true }],
    compute: (v) => { const wr = safeDiv(n(v.won), n(v.opp)) * 100; const closed = n(v.won) + n(v.lost); const wrClosed = safeDiv(n(v.won), closed) * 100; return { primary: { label: "Opportunity win rate", value: pct(wr, 1), sub: `${num(n(v.won))} won of ${num(n(v.opp))} opportunities` }, tiles: [{ label: "Win rate (closed only)", value: pct(wrClosed, 1) }, { label: "Still open", value: num(Math.max(0, n(v.opp) - closed)) }, { label: "Won value", value: n(v.value) ? money(n(v.value) * n(v.won)) : "—" }] }; },
    formula: "Win rate = deals won ÷ total opportunities × 100",
  },
  "sales-cycle": {
    inputs: [{ key: "deals", label: "Deals closed in period", type: "number", default: 12, half: true }, { key: "totalDays", label: "Total days (first contact → close, summed)", type: "days", default: 540, half: true }, { key: "leads", label: "Leads entering pipeline / month", type: "number", default: 40, half: true }, { key: "wr", label: "Win rate", type: "percent", default: 25, half: true }],
    compute: (v) => { const avg = safeDiv(n(v.totalDays), n(v.deals)); return { primary: { label: "Average sales cycle", value: `${num(avg, 1)} days`, sub: `≈ ${num(avg / 7, 1)} weeks per deal` }, tiles: [{ label: "Deals / month (expected)", value: num(n(v.leads) * (n(v.wr) / 100), 1) }, { label: "Pipeline in flight", value: num(n(v.leads) * (avg / 30), 0), sub: "leads open at any time" }], insight: avg > 90 ? "Long cycle: add urgency (limited offers), simplify approvals, or qualify harder up-front." : "Short cycle: focus on volume and follow-up cadence." }; },
    formula: "Avg cycle = Σ days to close ÷ deals closed",
  },
  "forecast-accuracy": {
    inputs: [{ key: "f", label: "Forecast sales", type: "currency", default: 1000000, half: true }, { key: "a", label: "Actual sales", type: "currency", default: 880000, half: true }],
    compute: (v) => { const err = Math.abs(n(v.a) - n(v.f)); const acc = Math.max(0, 100 - safeDiv(err, n(v.a)) * 100); const bias = safeDiv(n(v.f) - n(v.a), n(v.a)) * 100; return { primary: { label: "Forecast accuracy", value: pct(acc, 1) }, tiles: [{ label: "Absolute error", value: money(err) }, { label: "Bias", value: `${bias > 0 ? "+" : ""}${num(bias, 1)}%`, sub: bias > 0 ? "over-forecast" : "under-forecast", tone: Math.abs(bias) > 15 ? "warn" : "default" }], insight: acc >= 90 ? "Excellent — forecasts are reliable for planning stock and cash." : acc >= 75 ? "Fair — review assumptions on seasonality and pipeline." : "Weak — rebuild the forecast from bottom-up pipeline data." }; },
    formula: "Accuracy = 100 − |actual − forecast| ÷ actual × 100",
  },
  "revenue-growth": {
    inputs: [{ key: "prev", label: "Previous period revenue", type: "currency", default: 850000, half: true }, { key: "curr", label: "Current period revenue", type: "currency", default: 1020000, half: true }, { key: "periods", label: "Periods between (for CAGR)", type: "number", default: 1, half: true, step: 1, min: 1 }],
    compute: (v) => { const g = safeDiv(n(v.curr) - n(v.prev), n(v.prev)) * 100; const cagr = n(v.prev) > 0 ? (Math.pow(n(v.curr) / n(v.prev), 1 / Math.max(1, n(v.periods))) - 1) * 100 : 0; return { primary: { label: "Revenue growth", value: `${g >= 0 ? "+" : ""}${num(g, 1)}%`, sub: `${money(n(v.curr) - n(v.prev))} change` }, tiles: [{ label: "Compound growth / period", value: pct(cagr, 2) }, { label: "Next period at this rate", value: money(n(v.curr) * (1 + g / 100)) }], bars: [{ label: "Previous", value: n(v.prev), display: money(n(v.prev)), tone: "muted" }, { label: "Current", value: n(v.curr), display: money(n(v.curr)) }] }; },
    formula: "Growth = (current − previous) ÷ previous × 100",
  },
  "engagement-rate": {
    inputs: [{ key: "platform", label: "Platform", type: "select", default: "instagram", options: [{ value: "instagram", label: "Instagram" }, { value: "facebook", label: "Facebook" }, { value: "linkedin", label: "LinkedIn" }, { value: "x", label: "X / Twitter" }], half: true }, { key: "followers", label: "Followers", type: "number", default: 12000, half: true }, { key: "reach", label: "Post reach / impressions", type: "number", default: 8000, half: true }, { key: "likes", label: "Likes / reactions", type: "number", default: 420, half: true }, { key: "comments", label: "Comments", type: "number", default: 35, half: true }, { key: "shares", label: "Shares / reposts", type: "number", default: 18, half: true }, { key: "saves", label: "Saves", type: "number", default: 60, half: true }],
    compute: (v) => { const eng = n(v.likes) + n(v.comments) + n(v.shares) + n(v.saves); const erF = safeDiv(eng, n(v.followers)) * 100; const erR = safeDiv(eng, n(v.reach)) * 100; const bench: Record<string, number> = { instagram: 1.5, facebook: 0.6, linkedin: 2, x: 0.5 }; const b = bench[String(v.platform)] ?? 1; return { primary: { label: "Engagement rate (by followers)", value: pct(erF, 2), sub: `${num(eng)} total engagements` }, tiles: [{ label: "Engagement by reach", value: pct(erR, 2) }, { label: "Industry benchmark", value: pct(b, 1) }, { label: "vs benchmark", value: `${num(safeDiv(erF, b), 1)}×`, tone: erF >= b ? "accent" : "warn" }], bars: [{ label: "Likes", value: n(v.likes) }, { label: "Comments", value: n(v.comments) }, { label: "Shares", value: n(v.shares) }, { label: "Saves", value: n(v.saves) }] }; },
    formula: "ER = (likes + comments + shares + saves) ÷ followers × 100",
  },
  "csat-calculator": {
    inputs: [{ key: "sat", label: "Satisfied responses (4 & 5 stars)", type: "number", default: 172, half: true }, { key: "total", label: "Total survey responses", type: "number", default: 210, half: true }],
    compute: (v) => { const c = safeDiv(n(v.sat), n(v.total)) * 100; return { primary: { label: "CSAT score", value: pct(c, 1), sub: `${num(n(v.sat))} happy out of ${num(n(v.total))}` }, tiles: [{ label: "Unsatisfied", value: num(n(v.total) - n(v.sat)), tone: "warn" }, { label: "Rating", value: c >= 85 ? "Excellent" : c >= 70 ? "Good" : c >= 50 ? "Average" : "Poor", tone: c >= 70 ? "accent" : "danger" }] }; },
    formula: "CSAT = satisfied responses ÷ total responses × 100",
  },
  "fcr-rate": {
    inputs: [{ key: "first", label: "Issues resolved on first contact", type: "number", default: 310, half: true }, { key: "total", label: "Total issues / tickets", type: "number", default: 400, half: true }],
    compute: (v) => { const f = safeDiv(n(v.first), n(v.total)) * 100; return { primary: { label: "First contact resolution", value: pct(f, 1) }, tiles: [{ label: "Needed follow-up", value: num(n(v.total) - n(v.first)) }, { label: "Benchmark", value: "70–79%" }], insight: f >= 80 ? "World-class. Customers rarely need to contact you twice." : f >= 70 ? "On par with industry. Empower agents with a knowledge base to go higher." : "Below average — look for issues that need escalation and fix root causes." }; },
    formula: "FCR = resolved on first contact ÷ total issues × 100",
  },
  "first-response-time": {
    inputs: [
      { key: "cn", label: "Calls handled", type: "number", default: 120, half: true, group: "Calls" }, { key: "cm", label: "Avg wait per call", type: "number", default: 3, half: true, group: "Calls", hint: "minutes" },
      { key: "en", label: "Emails answered", type: "number", default: 80, half: true, group: "Email" }, { key: "em", label: "Avg first reply", type: "hours", default: 6, half: true, group: "Email" },
      { key: "wn", label: "WhatsApp chats", type: "number", default: 200, half: true, group: "WhatsApp" }, { key: "wm", label: "Avg first reply", type: "number", default: 12, half: true, group: "WhatsApp", hint: "minutes" },
    ],
    compute: (v) => { const cM = n(v.cn) * n(v.cm), eM = n(v.en) * n(v.em) * 60, wM = n(v.wn) * n(v.wm); const total = n(v.cn) + n(v.en) + n(v.wn); const avg = safeDiv(cM + eM + wM, total); const fmt = (m: number) => (m >= 60 ? `${num(m / 60, 1)} h` : `${num(m, 0)} min`); return { primary: { label: "Average first response time", value: fmt(avg), sub: `across ${num(total)} interactions` }, bars: [{ label: "Calls", value: n(v.cm), display: fmt(n(v.cm)) }, { label: "Email", value: n(v.em) * 60, display: fmt(n(v.em) * 60) }, { label: "WhatsApp", value: n(v.wm), display: fmt(n(v.wm)) }], insight: "Targets: calls < 1 min wait, WhatsApp < 15 min, email < 4 hours." }; },
    formula: "Weighted average = Σ (count × avg time) ÷ Σ count",
  },
  "nps-calculator": {
    inputs: [{ key: "p", label: "Promoters (9–10)", type: "number", default: 120, half: true }, { key: "pa", label: "Passives (7–8)", type: "number", default: 60, half: true }, { key: "d", label: "Detractors (0–6)", type: "number", default: 30, half: true }],
    compute: (v) => { const t = n(v.p) + n(v.pa) + n(v.d); const nps = safeDiv(n(v.p) - n(v.d), t) * 100; return { primary: { label: "Net Promoter Score", value: `${nps >= 0 ? "+" : ""}${num(nps, 0)}`, sub: `${num(t)} responses` }, tiles: [{ label: "Promoters", value: pct(safeDiv(n(v.p), t) * 100, 0), tone: "accent" }, { label: "Passives", value: pct(safeDiv(n(v.pa), t) * 100, 0) }, { label: "Detractors", value: pct(safeDiv(n(v.d), t) * 100, 0), tone: "danger" }], insight: nps >= 70 ? "World-class loyalty." : nps >= 30 ? "Good — customers recommend you more than they complain." : nps >= 0 ? "Room to improve — talk to detractors this week." : "Negative — more detractors than promoters; prioritise service recovery." }; },
    formula: "NPS = % promoters − % detractors (range −100 to +100)",
  },

  /* ─────────── Finance ─────────── */
  "ebitda-calculator": {
    inputs: [{ key: "ni", label: "Net income (PAT)", type: "currency", default: 1200000, half: true }, { key: "int", label: "Interest expense", type: "currency", default: 250000, half: true }, { key: "tax", label: "Taxes", type: "currency", default: 400000, half: true }, { key: "dep", label: "Depreciation", type: "currency", default: 300000, half: true }, { key: "amort", label: "Amortization", type: "currency", default: 50000, half: true }, { key: "rev", label: "Revenue", type: "currency", default: 8000000, half: true }],
    compute: (v) => { const ebitda = n(v.ni) + n(v.int) + n(v.tax) + n(v.dep) + n(v.amort); const ebit = ebitda - n(v.dep) - n(v.amort); return { primary: { label: "EBITDA", value: money(ebitda), sub: `${pct(safeDiv(ebitda, n(v.rev)) * 100, 1)} EBITDA margin` }, tiles: [{ label: "EBIT", value: money(ebit) }, { label: "Net margin", value: pct(safeDiv(n(v.ni), n(v.rev)) * 100, 1) }, { label: "Interest coverage", value: `${num(safeDiv(ebit, n(v.int)), 1)}×` }], bars: [{ label: "Net income", value: n(v.ni), display: money(n(v.ni)) }, { label: "+ Interest", value: n(v.int), display: money(n(v.int)), tone: "muted" }, { label: "+ Taxes", value: n(v.tax), display: money(n(v.tax)), tone: "muted" }, { label: "+ D&A", value: n(v.dep) + n(v.amort), display: money(n(v.dep) + n(v.amort)), tone: "muted" }] }; },
    formula: "EBITDA = net income + interest + taxes + depreciation + amortization",
  },
  "cagr-calculator": {
    inputs: [{ key: "start", label: "Initial value", type: "currency", default: 500000, half: true }, { key: "end", label: "Final value", type: "currency", default: 1250000, half: true }, { key: "years", label: "Duration", type: "years", default: 5, half: true, step: 0.5 }],
    compute: (v) => { const c = n(v.start) > 0 && n(v.years) > 0 ? (Math.pow(n(v.end) / n(v.start), 1 / n(v.years)) - 1) * 100 : 0; const abs = safeDiv(n(v.end) - n(v.start), n(v.start)) * 100; return { primary: { label: "Compound annual growth rate", value: pct(c, 2), sub: `${money(n(v.start))} → ${money(n(v.end))} over ${num(n(v.years), 1)} years` }, tiles: [{ label: "Absolute growth", value: pct(abs, 1) }, { label: "Multiple", value: `${num(safeDiv(n(v.end), n(v.start)), 2)}×` }, { label: "Doubling time", value: c > 0 ? `${num(Math.log(2) / Math.log(1 + c / 100), 1)} yrs` : "—" }] }; },
    formula: "CAGR = (final ÷ initial)^(1 ÷ years) − 1",
  },
  "roi-calculator": {
    inputs: [{ key: "inv", label: "Amount invested", type: "currency", default: 300000, half: true }, { key: "ret", label: "Total returned / current value", type: "currency", default: 420000, half: true }, { key: "years", label: "Holding period", type: "years", default: 2, half: true, step: 0.5 }],
    compute: (v) => { const gain = n(v.ret) - n(v.inv); const roi = safeDiv(gain, n(v.inv)) * 100; const ann = n(v.inv) > 0 && n(v.years) > 0 ? (Math.pow(n(v.ret) / n(v.inv), 1 / n(v.years)) - 1) * 100 : 0; return { primary: { label: "Return on investment", value: pct(roi, 1), sub: `${gain >= 0 ? "Gain" : "Loss"} of ${money(Math.abs(gain))}` }, tiles: [{ label: "Annualised return", value: pct(ann, 2) }, { label: "Net gain", value: money(gain), tone: gain >= 0 ? "accent" : "danger" }] }; },
    formula: "ROI = (returned − invested) ÷ invested × 100",
  },
  "gross-margin": {
    inputs: [{ key: "rev", label: "Revenue / selling price", type: "currency", default: 250000, half: true }, { key: "cogs", label: "Cost of goods sold", type: "currency", default: 160000, half: true }],
    compute: (v) => { const gp = n(v.rev) - n(v.cogs); const gm = safeDiv(gp, n(v.rev)) * 100; const mu = safeDiv(gp, n(v.cogs)) * 100; return { primary: { label: "Gross margin", value: pct(gm, 1), sub: `Gross profit ${money(gp)}` }, tiles: [{ label: "Markup on cost", value: pct(mu, 1) }, { label: "Cost ratio", value: pct(100 - gm, 1) }], bars: [{ label: "COGS", value: n(v.cogs), display: money(n(v.cogs)), tone: "muted" }, { label: "Gross profit", value: gp, display: money(gp) }] }; },
    formula: "Gross margin = (revenue − COGS) ÷ revenue × 100 · markup = gross profit ÷ COGS",
  },
  "net-profit-margin": {
    inputs: [{ key: "rev", label: "Total revenue", type: "currency", default: 1200000, group: "Income" }, { key: "cogs", label: "Cost of goods sold", type: "currency", default: 600000, half: true, group: "Expenses" }, { key: "opex", label: "Operating expenses (rent, salaries)", type: "currency", default: 300000, half: true, group: "Expenses" }, { key: "int", label: "Interest", type: "currency", default: 40000, half: true, group: "Expenses" }, { key: "tax", label: "Taxes", type: "currency", default: 60000, half: true, group: "Expenses" }],
    compute: (v) => { const exp = n(v.cogs) + n(v.opex) + n(v.int) + n(v.tax); const np = n(v.rev) - exp; const m = safeDiv(np, n(v.rev)) * 100; return { primary: { label: "Net profit margin", value: pct(m, 1), sub: `Net profit ${money(np)}` }, tiles: [{ label: "Total expenses", value: money(exp) }, { label: "Operating margin", value: pct(safeDiv(n(v.rev) - n(v.cogs) - n(v.opex), n(v.rev)) * 100, 1) }], insight: m >= 15 ? "Strong bottom line for a small business." : m >= 5 ? "Typical for retail — watch operating costs." : "Thin or negative — review pricing and fixed costs." }; },
    formula: "Net margin = (revenue − all expenses) ÷ revenue × 100",
  },
  "contribution-margin": {
    inputs: [{ key: "price", label: "Selling price per unit", type: "currency", default: 500, half: true }, { key: "vc", label: "Variable cost per unit", type: "currency", default: 320, half: true }, { key: "units", label: "Units sold", type: "number", default: 1000, half: true }, { key: "fixed", label: "Fixed costs (rent, salaries)", type: "currency", default: 120000, half: true }],
    compute: (v) => { const cm = n(v.price) - n(v.vc); const ratio = safeDiv(cm, n(v.price)) * 100; const total = cm * n(v.units); const be = safeDiv(n(v.fixed), cm); return { primary: { label: "Contribution margin per unit", value: inr(cm), sub: `${pct(ratio, 1)} of price` }, tiles: [{ label: "Total contribution", value: money(total) }, { label: "Break-even units", value: num(Math.ceil(be)) }, { label: "Profit after fixed costs", value: money(total - n(v.fixed)), tone: total >= n(v.fixed) ? "accent" : "danger" }] }; },
    formula: "CM = price − variable cost · break-even units = fixed costs ÷ CM",
  },
  "budget-variance": {
    inputs: [{ key: "br", label: "Budgeted revenue", type: "currency", default: 1000000, half: true, group: "Revenue" }, { key: "ar", label: "Actual revenue", type: "currency", default: 940000, half: true, group: "Revenue" }, { key: "be", label: "Budgeted expenses", type: "currency", default: 700000, half: true, group: "Expenses" }, { key: "ae", label: "Actual expenses", type: "currency", default: 735000, half: true, group: "Expenses" }],
    compute: (v) => { const rv = n(v.ar) - n(v.br); const ev = n(v.be) - n(v.ae); const bp = n(v.br) - n(v.be), ap = n(v.ar) - n(v.ae); return { primary: { label: "Net variance (profit)", value: `${ap - bp >= 0 ? "+" : "−"}${money(Math.abs(ap - bp))}`, sub: `Budgeted profit ${money(bp)} · actual ${money(ap)}` }, tiles: [{ label: "Revenue variance", value: `${rv >= 0 ? "+" : "−"}${money(Math.abs(rv))}`, sub: `${pct(safeDiv(rv, n(v.br)) * 100, 1)} · ${rv >= 0 ? "favourable" : "unfavourable"}`, tone: rv >= 0 ? "accent" : "danger" }, { label: "Expense variance", value: `${ev >= 0 ? "+" : "−"}${money(Math.abs(ev))}`, sub: `${pct(safeDiv(ev, n(v.be)) * 100, 1)} · ${ev >= 0 ? "favourable" : "unfavourable"}`, tone: ev >= 0 ? "accent" : "danger" }], bars: [{ label: "Budget rev", value: n(v.br), display: money(n(v.br)), tone: "muted" }, { label: "Actual rev", value: n(v.ar), display: money(n(v.ar)) }, { label: "Budget exp", value: n(v.be), display: money(n(v.be)), tone: "muted" }, { label: "Actual exp", value: n(v.ae), display: money(n(v.ae)), tone: "warn" }] }; },
    formula: "Variance = actual − budget (revenue) · budget − actual (expenses); positive = favourable",
  },
  "profit-margin": {
    inputs: [{ key: "sp", label: "Selling price", type: "currency", default: 799, half: true, group: "Per unit" }, { key: "cp", label: "Product cost", type: "currency", default: 450, half: true, group: "Per unit" }, { key: "pack", label: "Packaging & shipping", type: "currency", default: 60, half: true, group: "Per unit" }, { key: "gw", label: "Payment gateway fee", type: "percent", default: 2, half: true, group: "Per unit", step: 0.1 }, { key: "other", label: "Other variable cost", type: "currency", default: 0, half: true, group: "Per unit" }, { key: "fixed", label: "Monthly fixed costs", type: "currency", default: 30000, half: true, group: "Business" }, { key: "units", label: "Units sold / month", type: "number", default: 200, half: true, group: "Business" }],
    compute: (v) => { const fee = n(v.sp) * (n(v.gw) / 100); const vc = n(v.cp) + n(v.pack) + fee + n(v.other); const profit = n(v.sp) - vc; const margin = safeDiv(profit, n(v.sp)) * 100; const markup = safeDiv(profit, n(v.cp)) * 100; const be = safeDiv(n(v.fixed), profit); const monthly = profit * n(v.units) - n(v.fixed); return { primary: { label: "Net profit margin", value: pct(margin, 1), sub: `${inr(profit)} profit per unit` }, tiles: [{ label: "Markup on cost", value: pct(markup, 1) }, { label: "Break-even units / mo", value: num(Math.ceil(be)) }, { label: "Monthly profit", value: money(monthly), tone: monthly >= 0 ? "accent" : "danger" }], rows: [["Selling price", inr(n(v.sp))], ["Product cost", `− ${inr(n(v.cp))}`], ["Packaging & shipping", `− ${inr(n(v.pack))}`], [`Gateway fee (${n(v.gw)}%)`, `− ${inr(fee)}`], n(v.other) ? ["Other", `− ${inr(n(v.other))}`] : null, ["Profit per unit", inr(profit)]] }; },
    formula: "Margin = (price − all variable costs) ÷ price · break-even = fixed ÷ profit per unit",
  },
  "upi-mdr-calculator": {
    inputs: [
      { key: "cat", label: "Merchant category", type: "select", default: "large", options: [{ value: "p2pm", label: "P2PM small merchant (turnover ≤ ₹40 lakh) — exempt" }, { value: "large", label: "Large merchant (P2M) — MDR applies" }, { value: "custom", label: "Custom rate" }] },
      { key: "amt", label: "Transaction amount", type: "currency", default: 5000, half: true },
      { key: "txns", label: "Transactions / month", type: "number", default: 800, half: true },
      { key: "rate", label: "MDR rate", type: "percent", default: 0.4, half: true, step: 0.05, showIf: (v) => v.cat === "custom" },
      { key: "cap", label: "Cap per transaction", type: "currency", default: 300, half: true, showIf: (v) => v.cat === "custom" },
      { key: "thresh", label: "Exempt below amount", type: "currency", default: 2000, half: true, showIf: (v) => v.cat !== "p2pm" },
    ],
    compute: (v) => { const cat = String(v.cat); const rate = cat === "p2pm" ? 0 : cat === "custom" ? n(v.rate) : 0.4; const cap = cat === "custom" ? n(v.cap) : 300; const thresh = cat === "p2pm" ? Infinity : n(v.thresh); const per = n(v.amt) < thresh ? 0 : Math.min(n(v.amt) * rate / 100, cap); const gst = per * 0.18; const monthly = (per + gst) * n(v.txns); return { primary: { label: "MDR per transaction", value: inr(per), sub: per ? `${rate}% capped at ${inr(cap, { decimals: 0 })} · + 18% GST = ${inr(per + gst)}` : "No MDR — exempt transaction" }, tiles: [{ label: "Net you receive", value: inr(n(v.amt) - per - gst) }, { label: "Effective rate", value: pct(safeDiv(per + gst, n(v.amt)) * 100, 3) }, { label: "Monthly MDR cost", value: money(monthly), tone: monthly ? "warn" : "accent" }], insight: cat === "p2pm" ? "Small merchants (P2PM) stay at zero MDR under the 2026 framework." : `Transactions below ${inr(thresh, { decimals: 0 })} are exempt; above it, ${rate}% applies with a ${inr(cap, { decimals: 0 })} cap. Defaults follow the 2026 NPCI framework — confirm your PSP's schedule.` }; },
    note: "Rates and caps are configurable — the 2026 framework values are defaults, not advice. See the UPI MDR 2026 guide for details.",
  },
  "seller-pricing": {
    inputs: [
      { key: "cost", label: "Product cost", type: "currency", default: 320, half: true, group: "Costs" }, { key: "pack", label: "Packaging", type: "currency", default: 25, half: true, group: "Costs" },
      { key: "l", label: "Length", type: "cm", default: 25, half: true, group: "Parcel" }, { key: "w", label: "Width", type: "cm", default: 18, half: true, group: "Parcel" }, { key: "h", label: "Height", type: "cm", default: 10, half: true, group: "Parcel" }, { key: "wt", label: "Actual weight", type: "kg", default: 0.6, half: true, group: "Parcel", step: 0.1 },
      { key: "ship", label: "Shipping rate per 0.5 kg", type: "currency", default: 45, half: true, group: "Marketplace" }, { key: "comm", label: "Platform commission", type: "percent", default: 12, half: true, group: "Marketplace" }, { key: "pay", label: "Payment / collection fee", type: "percent", default: 2, half: true, group: "Marketplace" }, { key: "gst", label: "GST on product", type: "percent", default: 12, half: true, group: "Marketplace" }, { key: "margin", label: "Target net margin", type: "percent", default: 20, half: true, group: "Marketplace" },
    ],
    compute: (v) => { const vol = (n(v.l) * n(v.w) * n(v.h)) / 5000; const charge = Math.max(vol, n(v.wt)); const slabs = Math.ceil(charge / 0.5); const shipping = slabs * n(v.ship); const base = n(v.cost) + n(v.pack) + shipping; const m = n(v.margin) / 100, c = n(v.comm) / 100, p = n(v.pay) / 100; // price*(1 - c - p - m) = base  (fees on price)
      const priceExGst = safeDiv(base, 1 - c - p - m); const listing = priceExGst * (1 + n(v.gst) / 100); const fees = priceExGst * (c + p); const profit = priceExGst - fees - base; return { primary: { label: "Recommended listing price (incl. GST)", value: inr(listing, { decimals: 0 }), sub: `${inr(priceExGst)} before GST` }, rows: [["Volumetric weight", `${num(vol, 2)} kg`], ["Chargeable weight", `${num(charge, 2)} kg (${slabs} × 0.5 kg)`], ["Shipping", inr(shipping)], ["Landed cost (product + pack + ship)", inr(base)], [`Platform + payment fees (${n(v.comm) + n(v.pay)}%)`, inr(fees)], ["Net profit per order", inr(profit)]], tiles: [{ label: "Net payout", value: inr(priceExGst - fees) }, { label: "Profit", value: inr(profit), tone: "accent" }, { label: "Margin on price", value: pct(safeDiv(profit, priceExGst) * 100, 1) }] }; },
    formula: "Price = landed cost ÷ (1 − commission − payment fee − target margin); listing = price × (1 + GST)",
  },
  "freelance-rate": {
    inputs: [{ key: "income", label: "Target annual take-home", type: "currency", default: 1200000, half: true, group: "Goals" }, { key: "exp", label: "Annual business expenses", type: "currency", default: 150000, half: true, group: "Goals", help: "software, laptop, internet, accountant" }, { key: "tax", label: "Tax & buffer", type: "percent", default: 20, half: true, group: "Goals" }, { key: "hpw", label: "Billable hours / week", type: "hours", default: 25, half: true, group: "Time" }, { key: "off", label: "Weeks off per year", type: "number", default: 6, half: true, group: "Time" }, { key: "util", label: "Utilisation (paid work share)", type: "percent", default: 75, half: true, group: "Time" }],
    compute: (v) => { const gross = (n(v.income) + n(v.exp)) / (1 - n(v.tax) / 100); const weeks = 52 - n(v.off); const hours = n(v.hpw) * weeks * (n(v.util) / 100); const hourly = safeDiv(gross, hours); return { primary: { label: "Minimum hourly rate", value: inr(Math.ceil(hourly / 50) * 50, { decimals: 0 }), sub: `${num(hours)} billable hours a year` }, tiles: [{ label: "Day rate (8 h)", value: inr(Math.ceil(hourly * 8 / 500) * 500, { decimals: 0 }) }, { label: "Monthly target", value: money(gross / 12) }, { label: "Gross needed / yr", value: money(gross) }], insight: "Quote projects at rate × estimated hours × 1.2 — revisions and admin always take longer than planned." }; },
    formula: "Rate = (income + expenses) ÷ (1 − tax%) ÷ (billable hrs/week × working weeks × utilisation)",
  },
  "hra-exemption": {
    inputs: [{ key: "basic", label: "Basic salary (annual)", type: "currency", default: 600000, half: true }, { key: "da", label: "Dearness allowance (annual)", type: "currency", default: 0, half: true }, { key: "hra", label: "HRA received (annual)", type: "currency", default: 240000, half: true }, { key: "rent", label: "Rent paid (annual)", type: "currency", default: 216000, half: true }, { key: "metro", label: "City", type: "select", default: "metro", options: [{ value: "metro", label: "Metro (Delhi, Mumbai, Kolkata, Chennai) — 50%" }, { value: "non", label: "Non-metro — 40%" }] }],
    compute: (v) => { const sal = n(v.basic) + n(v.da); const a = n(v.hra); const b = Math.max(0, n(v.rent) - sal * 0.1); const c = sal * (v.metro === "metro" ? 0.5 : 0.4); const ex = Math.max(0, Math.min(a, b, c)); return { primary: { label: "HRA exemption (Sec 10(13A))", value: money(ex), sub: `Taxable HRA ${money(a - ex)}` }, rows: [["(a) HRA received", money(a)], ["(b) Rent − 10% of salary", money(b)], [`(c) ${v.metro === "metro" ? "50" : "40"}% of salary`, money(c)], ["Exempt = least of a, b, c", money(ex)]], insight: n(v.rent) > 100000 ? "Rent above ₹1 lakh a year — you must furnish the landlord's PAN to your employer." : undefined }; },
    note: "Available only under the old tax regime. Salary = basic + DA (if part of retirement benefits).",
  },
  "advance-tax": {
    inputs: [{ key: "tax", label: "Estimated total tax for the year", type: "currency", default: 180000, half: true, help: "including cess, after rebate" }, { key: "tds", label: "TDS / TCS already deducted", type: "currency", default: 30000, half: true }, { key: "paid", label: "Advance tax already paid", type: "currency", default: 0, half: true }, { key: "presumptive", label: "Presumptive scheme (44AD/44ADA)?", type: "select", default: "no", options: [{ value: "no", label: "No — 4 instalments" }, { value: "yes", label: "Yes — single instalment by 15 March" }], half: true }],
    compute: (v) => { const net = Math.max(0, n(v.tax) - n(v.tds)); const due = Math.max(0, net - n(v.paid)); const app = net >= 10000; const fy = new Date().getMonth() >= 3 ? new Date().getFullYear() : new Date().getFullYear() - 1; const sched = v.presumptive === "yes" ? [["15 Mar " + (fy + 1), 100]] : [["15 Jun " + fy, 15], ["15 Sep " + fy, 45], ["15 Dec " + fy, 75], ["15 Mar " + (fy + 1), 100]]; let prev = 0; const rows = sched.map(([d, p]) => { const cum = net * (Number(p) / 100); const inst = cum - prev; prev = cum; return [`${d} · ${p}% cumulative`, `${money(inst)} (cum. ${money(cum)})`] as [string, string]; }); return { primary: { label: app ? "Net advance tax payable" : "Advance tax not applicable", value: money(due), sub: app ? `Total liability ${money(net)} after TDS` : "Liability after TDS is below ₹10,000" }, rows: app ? rows : undefined, insight: "Shortfall attracts interest under Sections 234B (1%/month) and 234C. Senior citizens without business income are exempt." }; },
    note: "Financial year runs April–March. Instalment percentages are cumulative of the net liability.",
  },
  "late-payment-interest": {
    inputs: [{ key: "amt", label: "Invoice / overdue amount", type: "currency", default: 250000, half: true }, { key: "due", label: "Due date (agreed or 45 days)", type: "date", default: addDaysISO(todayISO(), -75), half: true }, { key: "pay", label: "Payment date / today", type: "date", default: todayISO(), half: true }, { key: "mode", label: "Interest basis", type: "select", default: "msmed", options: [{ value: "msmed", label: "MSMED Act — 3× RBI bank rate, compounded monthly" }, { value: "simple", label: "Agreed contract rate — simple interest" }], half: true }, { key: "bank", label: "RBI bank rate", type: "percent", default: 5.5, half: true, step: 0.25, showIf: (v) => v.mode === "msmed" }, { key: "rate", label: "Agreed annual rate", type: "percent", default: 18, half: true, showIf: (v) => v.mode === "simple" }],
    compute: (v) => { const d = Math.max(0, days(String(v.due), String(v.pay))); const amt = n(v.amt); let interest = 0, annual = 0; if (v.mode === "msmed") { annual = n(v.bank) * 3; const months = d / 30.4375; interest = amt * (Math.pow(1 + annual / 100 / 12, months) - 1); } else { annual = n(v.rate); interest = amt * (annual / 100) * (d / 365); } return { primary: { label: "Interest payable", value: inr(interest), sub: `${d} days overdue at ${num(annual, 2)}% p.a.` }, tiles: [{ label: "Total payable", value: inr(amt + interest), tone: "danger" }, { label: "Per day", value: inr(safeDiv(interest, d || 1)) }, { label: "Effective rate", value: pct(safeDiv(interest, amt) * 100, 2) }], insight: v.mode === "msmed" ? "Under Section 16 of the MSMED Act, buyers owe compound interest (monthly rests) at three times the RBI bank rate from the appointed day. File on MSME Samadhaan for recovery." : undefined }; },
    note: "Payment to a registered MSME is due within 45 days of acceptance (or 15 days if no written agreement).",
  },

  /* ─────────── HR ─────────── */
  "employee-cost": {
    inputs: [{ key: "gross", label: "Gross monthly salary", type: "currency", default: 40000, half: true }, { key: "basicPct", label: "Basic as % of gross", type: "percent", default: 50, half: true }, { key: "pfCap", label: "PF on capped wage (₹15,000)?", type: "select", default: "yes", options: [{ value: "yes", label: "Yes — statutory minimum" }, { value: "no", label: "No — on full basic" }], half: true }, { key: "bonus", label: "Bonus provision", type: "percent", default: 8.33, half: true, step: 0.01 }, { key: "other", label: "Other benefits / month", type: "currency", default: 1500, half: true, help: "insurance, meals, transport" }],
    compute: (v) => { const gross = n(v.gross); const basic = gross * (n(v.basicPct) / 100); const pfWage = v.pfCap === "yes" ? Math.min(basic, 15000) : basic; const pf = pfWage * 0.13; const esi = gross <= 21000 ? gross * 0.0325 : 0; const grat = basic * 0.0481; const bonusBase = gross <= 21000 ? Math.min(basic, 7000) : 0; const bonus = bonusBase * (n(v.bonus) / 100); const monthly = gross + pf + esi + grat + bonus + n(v.other); return { primary: { label: "Fully-loaded monthly cost", value: money(monthly), sub: `${money(monthly * 12)} per year · ${pct(safeDiv(monthly - gross, gross) * 100, 1)} on top of gross` }, rows: [["Gross salary", money(gross)], ["Employer PF (12% + 1% admin)", money(pf)], ["Employer ESI (3.25%)", esi ? money(esi) : "Not applicable (> ₹21,000)"], ["Gratuity provision (4.81% of basic)", money(grat)], ["Statutory bonus provision", bonus ? money(bonus) : "Not applicable"], ["Other benefits", money(n(v.other))]], tiles: [{ label: "Annual CTC", value: money(monthly * 12) }, { label: "Statutory add-ons", value: money(pf + esi + grat + bonus) }] }; },
    note: "ESI applies where gross ≤ ₹21,000; bonus under the Payment of Bonus Act where wages ≤ ₹21,000 (computed on ₹7,000 or minimum wage).",
  },
  "statutory-bonus": {
    inputs: [{ key: "wage", label: "Monthly wage (basic + DA)", type: "currency", default: 15000, half: true }, { key: "minWage", label: "State minimum wage (monthly)", type: "currency", default: 0, half: true, help: "if higher than ₹7,000" }, { key: "months", label: "Months worked in the year", type: "months", default: 12, half: true, max: 12 }, { key: "pct", label: "Bonus declared", type: "percent", default: 8.33, half: true, step: 0.01, min: 8.33, max: 20 }],
    compute: (v) => { const eligible = n(v.wage) <= 21000 && n(v.months) >= 1; const ceiling = Math.max(7000, n(v.minWage)); const base = Math.min(n(v.wage), ceiling); const bonus = eligible ? base * (Math.min(20, Math.max(8.33, n(v.pct))) / 100) * n(v.months) : 0; return { primary: { label: eligible ? "Statutory bonus payable" : "Not eligible", value: money(bonus), sub: eligible ? `${num(n(v.pct), 2)}% of ${money(base)} × ${n(v.months)} months` : "Wage above ₹21,000/month or less than 30 days worked" }, tiles: [{ label: "Minimum (8.33%)", value: money(eligible ? base * 0.0833 * n(v.months) : 0) }, { label: "Maximum (20%)", value: money(eligible ? base * 0.2 * n(v.months) : 0) }] }; },
    note: "Payment of Bonus Act, 1965: eligibility wage ≤ ₹21,000; calculation ceiling ₹7,000 or minimum wage, whichever is higher; minimum 8.33%, maximum 20%; at least 30 working days.",
  },
  "notice-period": {
    inputs: [{ key: "res", label: "Resignation date", type: "date", default: todayISO(), half: true }, { key: "notice", label: "Notice period", type: "days", default: 60, half: true }, { key: "leave", label: "Leave balance adjusted against notice", type: "days", default: 0, half: true }, { key: "buyout", label: "Days bought out", type: "days", default: 0, half: true }, { key: "salary", label: "Monthly gross (for buyout cost)", type: "currency", default: 0, half: true }],
    compute: (v) => { const eff = Math.max(0, n(v.notice) - n(v.leave) - n(v.buyout)); const lwd = addDaysISO(String(v.res), eff - 1 < 0 ? 0 : eff - 1); const left = days(todayISO(), lwd); const cost = safeDiv(n(v.salary), 30) * n(v.buyout); return { primary: { label: "Last working day", value: fmtDate(lwd, "long"), sub: `${eff} days of effective notice` }, tiles: [{ label: "Days remaining", value: left >= 0 ? num(left) : "Completed", tone: "accent" }, { label: "Buyout cost", value: n(v.buyout) ? money(cost) : "—" }, { label: "Release / F&F by", value: fmtDate(addDaysISO(lwd, 45)) }], insight: "Final settlement (F&F) is typically processed within 30–45 days of the LWD. Keep your resignation acceptance email as proof of dates." }; },
    formula: "LWD = resignation date + (notice − leave adjusted − bought out) − 1",
  },
  "leave-balance": {
    inputs: [{ key: "quota", label: "Annual leave entitlement", type: "days", default: 24, half: true }, { key: "joined", label: "Date of joining", type: "date", default: todayISO().slice(0, 4) + "-01-01", half: true }, { key: "fy", label: "Leave year starts", type: "select", default: "jan", options: [{ value: "jan", label: "1 January" }, { value: "apr", label: "1 April" }], half: true }, { key: "carry", label: "Carried forward from last year", type: "days", default: 0, half: true }, { key: "used", label: "Leave taken this year", type: "days", default: 5, half: true }, { key: "asOf", label: "As of date", type: "date", default: todayISO(), half: true }],
    compute: (v) => { const asOf = new Date(String(v.asOf) + "T00:00:00"); const y = asOf.getFullYear(); const start = v.fy === "apr" ? new Date(asOf.getMonth() >= 3 ? y : y - 1, 3, 1) : new Date(y, 0, 1); const end = new Date(start); end.setFullYear(start.getFullYear() + 1); const join = new Date(String(v.joined) + "T00:00:00"); const from = join > start ? join : start; const yearDays = (end.getTime() - start.getTime()) / 86400000; const entitled = Math.max(0, (n(v.quota) * ((end.getTime() - from.getTime()) / 86400000)) / yearDays); const accrued = Math.max(0, (n(v.quota) * ((asOf.getTime() - from.getTime()) / 86400000)) / yearDays); const bal = entitled + n(v.carry) - n(v.used); return { primary: { label: "Leave balance (year-end entitlement)", value: `${num(bal, 1)} days`, sub: `${num(entitled, 1)} pro-rated + ${n(v.carry)} carried − ${n(v.used)} used` }, tiles: [{ label: "Accrued till date", value: `${num(accrued, 1)} d` }, { label: "Available now", value: `${num(Math.max(0, accrued + n(v.carry) - n(v.used)), 1)} d`, tone: "accent" }, { label: "Utilised", value: pct(safeDiv(n(v.used), entitled + n(v.carry)) * 100, 0) }] }; },
    formula: "Pro-rata = annual quota × days from joining (or year start) ÷ days in leave year",
  },

  /* ─────────── Logistics & operations ─────────── */
  "fuel-expense": {
    inputs: [{ key: "dist", label: "Trip distance (round trip)", type: "km", default: 38, half: true }, { key: "mileage", label: "Vehicle mileage", type: "number", default: 45, half: true, hint: "km per litre" }, { key: "fuel", label: "Fuel type", type: "select", default: "petrol", options: [{ value: "petrol", label: "Petrol" }, { value: "diesel", label: "Diesel" }, { value: "cng", label: "CNG (per kg)" }], half: true }, { key: "price", label: "Fuel price per litre", type: "currency", default: 96, half: true, step: 0.5 }, { key: "other", label: "Tolls, parking, driver", type: "currency", default: 0, half: true }, { key: "markup", label: "Customer markup", type: "percent", default: 20, half: true }],
    compute: (v) => { const litres = safeDiv(n(v.dist), n(v.mileage)); const fuel = litres * n(v.price); const cost = fuel + n(v.other); const billed = cost * (1 + n(v.markup) / 100); return { primary: { label: "Trip fuel cost", value: inr(fuel), sub: `${num(litres, 2)} ${v.fuel === "cng" ? "kg" : "L"} for ${n(v.dist)} km` }, tiles: [{ label: "Cost per km", value: inr(safeDiv(cost, n(v.dist))) }, { label: "Total trip cost", value: inr(cost) }, { label: "Bill to customer", value: inr(billed), tone: "accent" }], rows: [["Fuel", inr(fuel)], ["Other expenses", inr(n(v.other))], [`Markup ${n(v.markup)}%`, inr(billed - cost)], ["Billed", inr(billed)]] }; },
    formula: "Fuel = distance ÷ mileage × price per litre",
  },
  "volumetric-weight": {
    inputs: [{ key: "l", label: "Length", type: "cm", default: 40, half: true }, { key: "w", label: "Width", type: "cm", default: 30, half: true }, { key: "h", label: "Height", type: "cm", default: 20, half: true }, { key: "actual", label: "Actual weight", type: "kg", default: 2.5, half: true, step: 0.1 }, { key: "courier", label: "Courier divisor", type: "select", default: "5000", options: [{ value: "5000", label: "Delhivery / Ekart / DTDC / Xpressbees — 5000" }, { value: "4000", label: "Blue Dart / DHL / FedEx domestic — 4000" }, { value: "4500", label: "Ecom Express / Shadowfax — 4500" }, { value: "6000", label: "Air cargo intl. — 6000" }], half: true }, { key: "rate", label: "Rate per kg (optional)", type: "currency", default: 0, half: true }],
    compute: (v) => { const vol = (n(v.l) * n(v.w) * n(v.h)) / n(v.courier); const charge = Math.max(vol, n(v.actual)); const slab = Math.ceil(charge * 2) / 2; return { primary: { label: "Chargeable weight", value: `${num(slab, 1)} kg`, sub: `${vol > n(v.actual) ? "Volumetric" : "Actual"} weight applies (${num(charge, 2)} kg, rounded to 0.5 kg)` }, tiles: [{ label: "Volumetric weight", value: `${num(vol, 2)} kg`, tone: vol > n(v.actual) ? "warn" : "default" }, { label: "Actual weight", value: `${num(n(v.actual), 2)} kg` }, { label: "Est. freight", value: n(v.rate) ? inr(slab * n(v.rate)) : "—" }], insight: vol > n(v.actual) ? `Your box is “light but big” — reducing height by ${num(Math.max(0, n(v.h) - (n(v.actual) * n(v.courier)) / (n(v.l) * n(v.w))), 1)} cm would make actual weight apply.` : "Actual weight is higher than volumetric — packaging is efficient." }; },
    formula: "Volumetric (kg) = L × W × H (cm) ÷ divisor · chargeable = max(volumetric, actual)",
  },
  "order-accuracy": {
    inputs: [{ key: "total", label: "Orders shipped", type: "number", default: 1250, half: true }, { key: "wrong", label: "Orders with errors (wrong item, qty, damage)", type: "number", default: 23, half: true }, { key: "cost", label: "Avg cost per error (reship, refund)", type: "currency", default: 180, half: true }],
    compute: (v) => { const acc = safeDiv(n(v.total) - n(v.wrong), n(v.total)) * 100; return { primary: { label: "Order fulfilment accuracy", value: pct(acc, 2) }, tiles: [{ label: "Error rate", value: pct(100 - acc, 2), tone: 100 - acc > 2 ? "danger" : "default" }, { label: "Cost of errors", value: money(n(v.wrong) * n(v.cost)) }, { label: "Target", value: "≥ 99%" }] }; },
    formula: "Accuracy = (orders − error orders) ÷ orders × 100",
  },
  "on-time-delivery": {
    inputs: [{ key: "total", label: "Shipments delivered", type: "number", default: 980, half: true }, { key: "ontime", label: "Delivered on or before promise date", type: "number", default: 905, half: true }],
    compute: (v) => { const r = safeDiv(n(v.ontime), n(v.total)) * 100; return { primary: { label: "On-time delivery rate", value: pct(r, 1) }, tiles: [{ label: "Late deliveries", value: num(n(v.total) - n(v.ontime)), tone: "warn" }, { label: "Benchmark", value: "≥ 95%" }], insight: r >= 95 ? "Meets marketplace SLA norms." : "Below 95% — marketplaces may penalise; check courier cut-off times and pincode serviceability." }; },
    formula: "OTD = on-time shipments ÷ total shipments × 100",
  },
  "inventory-turnover": {
    inputs: [{ key: "cogs", label: "Cost of goods sold (period)", type: "currency", default: 2400000, half: true }, { key: "open", label: "Opening inventory", type: "currency", default: 500000, half: true }, { key: "close", label: "Closing inventory", type: "currency", default: 460000, half: true }, { key: "days", label: "Days in period", type: "days", default: 365, half: true }],
    compute: (v) => { const avg = (n(v.open) + n(v.close)) / 2; const t = safeDiv(n(v.cogs), avg); const dsi = safeDiv(n(v.days), t); return { primary: { label: "Inventory turnover", value: `${num(t, 2)}×`, sub: `Stock sold and replaced ${num(t, 1)} times in ${n(v.days)} days` }, tiles: [{ label: "Days sales of inventory", value: `${num(dsi, 0)} days` }, { label: "Average inventory", value: money(avg) }], insight: t < 4 ? "Slow-moving stock ties up cash — consider clearance offers on old SKUs." : t > 12 ? "Very fast turnover — watch for stock-outs." : "Healthy turnover for retail." }; },
    formula: "Turnover = COGS ÷ average inventory · DSI = days ÷ turnover",
  },
  "capacity-utilization": {
    inputs: [{ key: "actual", label: "Actual output (period)", type: "number", default: 8200, half: true }, { key: "max", label: "Maximum possible output", type: "number", default: 10000, half: true }, { key: "unit", label: "Unit", type: "text", default: "units" }],
    compute: (v) => { const u = safeDiv(n(v.actual), n(v.max)) * 100; return { primary: { label: "Capacity utilisation", value: pct(u, 1), sub: `${num(n(v.max) - n(v.actual))} ${v.unit} of idle capacity` }, tiles: [{ label: "Idle capacity", value: pct(100 - u, 1) }, { label: "Status", value: u > 90 ? "Near full" : u > 70 ? "Healthy" : "Under-utilised", tone: u > 90 ? "warn" : u > 70 ? "accent" : "danger" }], bars: [{ label: "Actual", value: n(v.actual) }, { label: "Max", value: n(v.max), tone: "muted" }] }; },
    formula: "Utilisation = actual output ÷ maximum capacity × 100",
  },
  "defect-rate": {
    inputs: [{ key: "insp", label: "Units inspected", type: "number", default: 5000, half: true }, { key: "def", label: "Defective units", type: "number", default: 65, half: true }, { key: "opp", label: "Defect opportunities per unit", type: "number", default: 1, half: true, help: "for DPMO" }],
    compute: (v) => { const r = safeDiv(n(v.def), n(v.insp)) * 100; const dpmo = safeDiv(n(v.def), n(v.insp) * Math.max(1, n(v.opp))) * 1e6; return { primary: { label: "Defect rate", value: pct(r, 2), sub: `First-pass yield ${pct(100 - r, 2)}` }, tiles: [{ label: "DPMO", value: num(dpmo, 0) }, { label: "Sigma level (approx.)", value: num(dpmo <= 3.4 ? 6 : dpmo <= 233 ? 5 : dpmo <= 6210 ? 4 : dpmo <= 66807 ? 3 : dpmo <= 308537 ? 2 : 1, 0) }, { label: "Good units", value: num(n(v.insp) - n(v.def)) }] }; },
    formula: "Defect rate = defective ÷ inspected × 100 · DPMO = defects ÷ (units × opportunities) × 1,000,000",
  },
  "discount-calculator": {
    inputs: [{ key: "mrp", label: "MRP / original price", type: "currency", default: 1999, half: true }, { key: "d1", label: "Discount", type: "percent", default: 30, half: true }, { key: "d2", label: "Extra discount (on discounted price)", type: "percent", default: 10, half: true }, { key: "flat", label: "Flat off (coupon)", type: "currency", default: 0, half: true }],
    compute: (v) => { const p1 = n(v.mrp) * (1 - n(v.d1) / 100); const p2 = p1 * (1 - n(v.d2) / 100); const final = Math.max(0, p2 - n(v.flat)); const saved = n(v.mrp) - final; const eff = safeDiv(saved, n(v.mrp)) * 100; return { primary: { label: "Final price", value: inr(final), sub: `You save ${inr(saved)} · effective ${pct(eff, 1)} off` }, rows: [["MRP", inr(n(v.mrp))], [`After ${n(v.d1)}% off`, inr(p1)], n(v.d2) ? [`After extra ${n(v.d2)}% off`, inr(p2)] : null, n(v.flat) ? ["After flat coupon", inr(final)] : null], insight: n(v.d2) ? `“${n(v.d1)}% + ${n(v.d2)}%” is not ${n(v.d1) + n(v.d2)}% — the second discount applies on the reduced price, so the real saving is ${pct(eff, 1)}.` : undefined }; },
    formula: "Final = MRP × (1 − d₁) × (1 − d₂) − flat off",
  },
};

export function make(slug: string) {
  const spec = specs[slug];
  const C = () => <SimpleCalc spec={spec} />;
  C.displayName = `Calc(${slug})`;
  return C;
}
