import type { ComponentType } from "react";

export type Loader = () => Promise<{ default: ComponentType }>;

/** slug → lazy component. Each tool is its own chunk. */
export const loaders: Record<string, Loader> = {
  // Billing & documents
  "gst-invoice": () => import("./billing/GstInvoice"),
  "proforma-invoice": () => import("./billing/ProformaInvoice"),
  "credit-note": () => import("./billing/CreditNote"),
  "debit-note": () => import("./billing/DebitNote"),
  "purchase-order": () => import("./billing/PurchaseOrder"),
  "service-quote": () => import("./billing/ServiceQuote"),
  "delivery-challan": () => import("./billing/DeliveryChallan"),
  "payment-receipt": () => import("./billing/PaymentReceipt"),
  "rent-receipt": () => import("./billing/RentReceipt"),
  "upi-standee": () => import("./shop/UpiStandee"),
  "menu-creator": () => import("./shop/MenuCreator"),
  "electricity-bill": () => import("./shop/ElectricityBill"),
  "telecom-bill": () => import("./shop/TelecomBill"),
  "broadband-bill": () => import("./shop/BroadbandBill"),
  "society-maintenance": () => import("./shop/SocietyMaintenance"),
  "medical-prescription": () => import("./shop/MedicalPrescription"),
  "hotel-voucher": () => import("./shop/HotelVoucher"),
  "boarding-pass": () => import("./shop/BoardingPass"),
  "movie-ticket": () => import("./shop/MovieTicket"),
  "gym-membership": () => import("./shop/GymMembership"),
  "wage-slip": () => import("./hr/WageSlip"),
  "experience-letter": () => import("./hr/ExperienceLetter"),
  "award-certificate": () => import("./hr/AwardCertificate"),
  "internship-certificate": () => import("./hr/InternshipCertificate"),
  "staff-id-card": () => import("./hr/StaffIdCard"),
  "shipping-label": () => import("./logistics/ShippingLabel"),
  "price-tag-generator": () => import("./logistics/PriceTag"),
  "letterhead": () => import("./freelancer/Letterhead"),
  "email-signature": () => import("./freelancer/EmailSignature"),
  "digital-signature": () => import("./freelancer/DigitalSignature"),
  "todo-list": () => import("./freelancer/TodoList"),
  "website-pdf-mockup": () => import("./media/WebsiteMockup"),
  // Calculators (declarative)
  "cac-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("cac-calculator") })),
  "retention-rate": () => import("./calc/specs").then((m) => ({ default: m.make("retention-rate") })),
  "referral-rate": () => import("./calc/specs").then((m) => ({ default: m.make("referral-rate") })),
  "roas-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("roas-calculator") })),
  "lead-conversion": () => import("./calc/specs").then((m) => ({ default: m.make("lead-conversion") })),
  "win-rate": () => import("./calc/specs").then((m) => ({ default: m.make("win-rate") })),
  "sales-cycle": () => import("./calc/specs").then((m) => ({ default: m.make("sales-cycle") })),
  "forecast-accuracy": () => import("./calc/specs").then((m) => ({ default: m.make("forecast-accuracy") })),
  "revenue-growth": () => import("./calc/specs").then((m) => ({ default: m.make("revenue-growth") })),
  "engagement-rate": () => import("./calc/specs").then((m) => ({ default: m.make("engagement-rate") })),
  "csat-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("csat-calculator") })),
  "fcr-rate": () => import("./calc/specs").then((m) => ({ default: m.make("fcr-rate") })),
  "first-response-time": () => import("./calc/specs").then((m) => ({ default: m.make("first-response-time") })),
  "nps-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("nps-calculator") })),
  "ebitda-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("ebitda-calculator") })),
  "cagr-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("cagr-calculator") })),
  "roi-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("roi-calculator") })),
  "gross-margin": () => import("./calc/specs").then((m) => ({ default: m.make("gross-margin") })),
  "net-profit-margin": () => import("./calc/specs").then((m) => ({ default: m.make("net-profit-margin") })),
  "contribution-margin": () => import("./calc/specs").then((m) => ({ default: m.make("contribution-margin") })),
  "budget-variance": () => import("./calc/specs").then((m) => ({ default: m.make("budget-variance") })),
  "profit-margin": () => import("./calc/specs").then((m) => ({ default: m.make("profit-margin") })),
  "upi-mdr-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("upi-mdr-calculator") })),
  "seller-pricing": () => import("./calc/specs").then((m) => ({ default: m.make("seller-pricing") })),
  "freelance-rate": () => import("./calc/specs").then((m) => ({ default: m.make("freelance-rate") })),
  "hra-exemption": () => import("./calc/specs").then((m) => ({ default: m.make("hra-exemption") })),
  "advance-tax": () => import("./calc/specs").then((m) => ({ default: m.make("advance-tax") })),
  "late-payment-interest": () => import("./calc/specs").then((m) => ({ default: m.make("late-payment-interest") })),
  "employee-cost": () => import("./calc/specs").then((m) => ({ default: m.make("employee-cost") })),
  "statutory-bonus": () => import("./calc/specs").then((m) => ({ default: m.make("statutory-bonus") })),
  "notice-period": () => import("./calc/specs").then((m) => ({ default: m.make("notice-period") })),
  "leave-balance": () => import("./calc/specs").then((m) => ({ default: m.make("leave-balance") })),
  "fuel-expense": () => import("./calc/specs").then((m) => ({ default: m.make("fuel-expense") })),
  "volumetric-weight": () => import("./calc/specs").then((m) => ({ default: m.make("volumetric-weight") })),
  "order-accuracy": () => import("./calc/specs").then((m) => ({ default: m.make("order-accuracy") })),
  "on-time-delivery": () => import("./calc/specs").then((m) => ({ default: m.make("on-time-delivery") })),
  "inventory-turnover": () => import("./calc/specs").then((m) => ({ default: m.make("inventory-turnover") })),
  "capacity-utilization": () => import("./calc/specs").then((m) => ({ default: m.make("capacity-utilization") })),
  "defect-rate": () => import("./calc/specs").then((m) => ({ default: m.make("defect-rate") })),
  "discount-calculator": () => import("./calc/specs").then((m) => ({ default: m.make("discount-calculator") })),
  // Calculators (custom)
  "gst-calculator": () => import("./calc/GstCalculator"),
  "percentage-calculator": () => import("./calc/PercentageCalculator"),
  "land-unit-converter": () => import("./calc/LandUnitConverter"),
  "emi-calculator": () => import("./calc/EmiCalculator"),
  "sip-calculator": () => import("./calc/SipCalculator"),
  "epf-gratuity": () => import("./calc/EpfGratuity"),
  "depreciation-calculator": () => import("./calc/Depreciation"),
  "tds-calculator": () => import("./calc/TdsCalculator"),
  "professional-tax": () => import("./calc/ProfessionalTax"),
  "business-days": () => import("./calc/BusinessDays"),
  "marketing-funnel": () => import("./calc/MarketingFunnel"),
  "income-tax": () => import("./calc/IncomeTax"),
  "in-hand-salary": () => import("./calc/InHandSalary"),
  "team-payroll": () => import("./calc/TeamPayroll"),
  "currency-converter": () => import("./calc/CurrencyConverter"),
  // QR, marketing, media & dev
  "url-qr": () => import("./marketing/UrlQr"),
  "vcard-qr": () => import("./marketing/VcardQr"),
  "wifi-qr": () => import("./marketing/WifiQr"),
  "whatsapp-direct": () => import("./marketing/WhatsappDirect"),
  "google-review": () => import("./marketing/GoogleReview"),
  "barcode-generator": () => import("./marketing/BarcodeGenerator"),
  "barcode-scanner": () => import("./marketing/BarcodeScanner"),
  "social-post": () => import("./marketing/SocialPost"),
  "favicon-generator": () => import("./media/FaviconGenerator"),
  "photo-resizer": () => import("./media/PhotoResizer"),
  "pdf-merge-split": () => import("./media/PdfMergeSplit"),
  "background-remover": () => import("./media/BackgroundRemover"),
  "image-ocr": () => import("./media/ImageOcr"),
  "json-base64": () => import("./media/JsonBase64"),
  "password-generator": () => import("./media/PasswordGenerator"),
  "password-strength": () => import("./media/PasswordStrength"),
  "word-counter": () => import("./media/WordCounter"),
  // Legal, SEO & reference
  "privacy-policy-generator": () => import("./legal/PrivacyPolicy"),
  "terms-generator": () => import("./legal/TermsGenerator"),
  "refund-policy": () => import("./legal/RefundPolicy"),
  "faq-schema": () => import("./legal/FaqSchema"),
  "robots-txt": () => import("./legal/RobotsTxt"),
  "schema-markup": () => import("./legal/SchemaMarkup"),
  "meta-tags": () => import("./legal/MetaTags"),
  "serp-preview": () => import("./legal/SerpSnippet"),
  "hsn-finder": () => import("./legal/HsnFinder"),
  "gst-calendar": () => import("./legal/GstCalendar"),
  "upi-mdr-guide": () => import("./legal/UpiMdrGuide"),
};
